name: Marvel # The name of the App
options: # Some general settings for the project
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 2 # indent by 2 spaces
  tabWidth: 2 # a tab is 2 spaces
  bundleIdPrefix: "com.github.jmlb23"
targets: # The List of our targets
  Marvel:
    type: application
    platform: iOS
    deploymentTarget: "15.4"
    preBuildScripts:
      - script: cd "$SRCROOT/../.." ; ./gradlew :mvvm:embedAndSignAppleFrameworkForXcode
        name: Gradle
    sources:
      - path: Marvel
    settings:
      configs:
        debug:
          FRAMEWORK_SEARCH_PATHS: "$SRCROOT/../../mvvm/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/"
          OTHER_LDFLAGS: "$(inherited) -framework Mvvm"
        release:
          FRAMEWORK_SEARCH_PATHS: "$SRCROOT/../../mvvm/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/"
          OTHER_LDFLAGS: "$(inherited) -framework Mvvm"
    dependencies:
      - sdk: SwiftUI.framework
    info:
      path: "Info.plist"
      version: 1
